language: node_js
node_js:
  # match this with .node-version:
  - "8.9.4"
env: NODE_ENV=production
jobs:
  include:
    - stage: test
      script: yarn run test
    - stage: deploy
      script: bin/deploy
      if: type = push
